apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-app
spec:
  selector:
    matchLabels:
      app: bad-app
  template:
    metadata:
      labels:
        app: bad-app
    spec:
      containers:
        - name: bad-app
          image: bad-image:latest
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: true
