apiVersion: v1
kind: Secret
metadata:
  name: secure-app-secrets
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
type: Opaque
stringData:
  DEMO_WEBHOOK_SIGNATURE: {{ .Values.secretEnv.DEMO_WEBHOOK_SIGNATURE | quote }}
