apiVersion: v1
kind: Service
metadata:
  name: secure-app
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
spec:
  selector:
    app: secure-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}
